1. What is a Python library? Why ^o we use Python libraries

In [4]:
#Answer-1
#A Python library is a collection of pre-written code modules that provide functionalities to accomplish specific tasks.
#We use Python libraries to save time and effort by leveraging existing code for tasks like data analysis, web development, machine learning, 
#and more, rather than writing everything from scratch.

2. What is the difference between Numpy array and List?

In [6]:
#Answer -2
#NumPy arrays are memory efficient, 
#faster for numerical operations, and homogeneous, meaning they store elements of the same data type.
#In contrast, lists are more versatile but less efficient for numerical computations and can store elements of different types.

3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [12]:
import numpy as np
array1 =np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]]) 
array1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [13]:
array1.shape

(3, 4)

In [14]:
array1.size

12

In [15]:
array1.ndim

2

4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [16]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
array2[0]

array([1, 2, 3, 4])

5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [22]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
array2[2][3]

12

6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [28]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [33]:
odd_indexed_element = array2[1::2,1::2]

In [34]:
odd_indexed_element

array([[6, 8]])

7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [38]:
np.random.random((3,3))

array([[0.9103952 , 0.59801979, 0.21507839],
       [0.84643946, 0.03593779, 0.97449569],
       [0.93344546, 0.37806895, 0.2137222 ]])

8. Describe the difference between np.random.rand and np.random.randn?

In [40]:
#np.random.rand: Generates random numbers from a uniform distribution over the interval [0, 1).
#np.random.randn: Generates random numbers from a standard normal distribution (mean=0, variance=1).


9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [43]:
arr3 = np.expand_dims(array2,axis = 0)
#axis =0 means expanded over row
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [45]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
array2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

11. Consider the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

In [53]:
A2 =np.array( [[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])
B2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8],[9, 10, 11, 12]])

In [55]:
#1. Index wise multiplication
A2*B2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [62]:
#2 Matix multiplication
#as we can see , we have to transpose one matrix because they have same shape that can cause error
A2 @ B2.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [63]:
#3  Add both the matices
A2 + B2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [64]:
#4 Subtact matix B from A
B2 - A2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [65]:
#5 Divide Matix B by A
B2/A2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

12. Which function in Numpy can be used to swap the byte order of an array?

In [66]:
#In NumPy, we can use the byteswap() function to swap the byte order of an array. 

13. What is the significance of the np.linalg.inv function?

In [67]:
#The np.linalg.inv function in NumPy computes the multiplicative inverse of a square matrix

14. What does the np.reshape function do, and how is it used?

In [68]:
#The np.reshape function in NumPy is used to change the shape of an array without changing its data.
#np.reshape(array, new_shape)
#for example
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Reshape the 1D array into a 2D array with 3 rows and 2 columns
new_arr = np.reshape(arr, (3, 2))

print(new_arr)



[[1 2]
 [3 4]
 [5 6]]


15. What is broadcasting in Numpy?

In [ ]:
#Broadcasting in NumPy is a feature that allows arrays with different shapes to be used together in 
#arithmetic operations by automatically adjusting their shapes to make them compatible. 